version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.11
  build:
    commands:
      - sam package --template-file template.yml --s3-bucket nhl-games-today-lambda --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml